/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grade12pat;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.NoSuchElementException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;

/**
 *
 * @author yaseen
 */
public class AddPatientPanel extends javax.swing.JPanel {

    Session session;
    RcdPatient patient;

    /**
     * Creates new form AddPatientPanel
     */
    public AddPatientPanel(Session session, RcdPatient patient) {
        initComponents();
        this.session = session;
        if (patient == null) {
            patient = new RcdPatient();

        }
        this.patient = patient;
        Calendar cal = Calendar.getInstance();
        fillInformation();

    }

    private void fillInformation() {
        txfFirstNames.setText(patient.getFirstnames());
        txfSurname.setText(patient.getSurname());
        txfCellphone.setText(patient.getCellphonenumber());
        txfIdNumber.setText(patient.getIdnumber());
        if (patient.getBirthday() != null) {
            Calendar cal = Calendar.getInstance();
            cal.setTime(patient.getBirthday());
            txfYear.setText(cal.get(cal.YEAR) + "");
            txfMonth.setText(cal.get(cal.MONTH) + "");
            txfDay.setText(cal.get(cal.DAY_OF_MONTH) + "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfIdNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfCellphone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfDay = new javax.swing.JFormattedTextField();
        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txfFirstNames = new javax.swing.JTextField();
        txfSurname = new javax.swing.JTextField();
        txfMonth = new javax.swing.JTextField();
        txfYear = new javax.swing.JTextField();

        txfIdNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfIdNumberFocusLost(evt);
            }
        });

        jLabel3.setText("id Number");

        jLabel4.setText("cellphone number");

        jLabel5.setText("birthday");

        txfDay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        btnAdd.setText("Save");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel1.setText("firstNames");

        btnCancel.setText("Billing Details");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel2.setText("lastNames");

        txfYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfYear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfDay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txfSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(txfFirstNames)
                                        .addComponent(txfIdNumber)
                                        .addComponent(txfCellphone)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfFirstNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txfCellphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel))
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        patient.setFirstnames(txfFirstNames.getText());
        patient.setSurname(txfSurname.getText());
        int year = Integer.parseInt(txfYear.getText());
        int month = Integer.parseInt(txfMonth.getText());
        int day = Integer.parseInt(txfDay.getText());
        System.out.println(year);
        patient.setBirthday(new Date(year - 1900, month, day));

        patient.setCellphonenumber(txfCellphone.getText());
        patient.setIdnumber(txfIdNumber.getText());

        EntityManager em = session.getEntityManager();
        // TODO try catch
        em.getTransaction().begin();
        if (patient.getId() == null) {
            patient.setId(session.nextId("patient"));
        }
        em.persist(patient);
        if (session.commit()) {
            session.closeTab();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        RcdPatientBillingDetails details;
        try {
            details = patient.getRcdPatientBillingDetailsList().iterator().next();
        } catch (NoSuchElementException e) {
            EntityManager em = session.getEntityManager();
            em.getTransaction().begin();
            details = new RcdPatientBillingDetails(session.nextId("PatientBillingDetails"));
            details.setPatientid(this.patient);
            patient.getRcdPatientBillingDetailsList().add(details);
            em.persist(details);
            em.getTransaction().commit();
        }
        session.showViewBillingDetails(details);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txfYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfYearActionPerformed

    private void txfIdNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfIdNumberFocusLost
        try {
            String id = txfIdNumber.getText();
            String year = id.substring(0, 2);
            int currentYear = Calendar.getInstance().get(Calendar.YEAR) - 2000;
            String month = id.substring(2, 4);
            String day = id.substring(4, 6);
            if (Integer.parseInt(year) <= currentYear) {
                year = "20" + year;
            } else {
                year = "19" + year;
            }
            txfYear.setText(year);
            txfMonth.setText(month);
            txfDay.setText(day);
        } catch (Exception e) {
        };
    }//GEN-LAST:event_txfIdNumberFocusLost

    private boolean validateID() {
        try {
            String id = txfIdNumber.getText();
            String year = id.substring(0, 2);
            String month = id.substring(2, 4);
            String day = id.substring(4, 6);
            boolean matches = txfYear.getText().substring(2) == year && month == txfMonth.getText() && day == txfDay.getText();
            if (!matches) {
                return false;
            }
            for (int i = 0; i < id.length(); ++i) {
                if (!Character.isDigit(id.charAt(i))) {
                    return false;
                }
            }
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txfCellphone;
    private javax.swing.JFormattedTextField txfDay;
    private javax.swing.JTextField txfFirstNames;
    private javax.swing.JTextField txfIdNumber;
    private javax.swing.JTextField txfMonth;
    private javax.swing.JTextField txfSurname;
    private javax.swing.JTextField txfYear;
    // End of variables declaration//GEN-END:variables
}
