/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grade12pat;

import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author yaseen
 */
public class MedicalAidPlan extends javax.swing.JPanel {
    RcdMedicalAidPlan plan;
    List<RcdMedicalAid> medicalAids;
    Session session;
    /**
     * Creates new form MedicalAidPlan
     */
    public MedicalAidPlan(Session session, RcdMedicalAidPlan plan) {
        initComponents();
        if (plan == null) {
            plan = new RcdMedicalAidPlan();
        }
        this.plan = plan;
        this.session = session;
        txfMember.setSession(session);
        fillInformation();
    }
    
    private void fillInformation() {
        medicalAids = session.sqlQuery("SELECT * FROM MEDICALAID", RcdMedicalAid.class);
        String stuff[] = new String[medicalAids.size()];
        for (int i = 0; i < stuff.length; ++i) {
            stuff[i] = medicalAids.get(i).getName();
        }
        cmbMedicalAid.setModel(new DefaultComboBoxModel<String>(stuff));
        if (plan.getMedicalaidid() != null) {
            cmbMedicalAid.setSelectedItem(plan.getMedicalaidid().getName());
        }
        txfMedicalAidNumber.setText(plan.getMedicalaidnumber());
        txfMember.setSelectedPatient(plan.getPrimarymemberid());
        txfMember.setActive();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbMedicalAid = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txfMedicalAidNumber = new javax.swing.JTextField();
        txfMember = new grade12pat.PatientTextField();

        jLabel1.setText("Medical Aid");

        cmbMedicalAid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMedicalAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMedicalAidActionPerformed(evt);
            }
        });

        jLabel2.setText("Medical Aid Number");

        jLabel3.setText("Name of Member");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMedicalAid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfMedicalAidNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(txfMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbMedicalAid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfMedicalAidNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMedicalAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMedicalAidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMedicalAidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        plan.setMedicalaidid(medicalAids.get(cmbMedicalAid.getSelectedIndex()));
        plan.setMedicalaidnumber(txfMedicalAidNumber.getText());
        plan.setPrimarymemberid(txfMember.getSelectedPatient());
        session.getEntityManager().getTransaction().begin();
        session.getEntityManager().persist(plan);
        if (session.commit()) {
            session.closeTab();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbMedicalAid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txfMedicalAidNumber;
    private grade12pat.PatientTextField txfMember;
    // End of variables declaration//GEN-END:variables
}
